### ISSUE TITLE
Vector database research

### ISSUE THREAD

**Issue by freedomofode** [uug-ai/facial-access-control#27]
Looking at different agile vector based databank frameworks.

These are the most promising free and open source databases:
1) Quadrant
2) Chroma
3) Milvus

**Comment by freedomofode** [comment]
Qdrant is chosen because it satisfies all our needs: 

Open Source & Free Forever
Self-Hosted
Full-Featured
Organized Community Support
Learning Resources & Docs
UI

**Comment by cedricve** [comment]
Looks like a valid choice @freedomofode
